# Generated by Django 2.1 on 2020-04-12 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='res_address',
            field=models.CharField(default=123, max_length=2083),
            preserve_default=False,
        ),
    ]
