# Generated by Django 2.1 on 2020-04-12 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_res_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='res_address',
        ),
        migrations.AddField(
            model_name='product',
            name='rest_address',
            field=models.CharField(max_length=2083, null=True),
        ),
    ]
