# Generated by Django 2.1 on 2020-04-16 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200412_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cuisines',
            field=models.CharField(max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='location',
            field=models.CharField(max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='timings_perks',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
