# Generated by Django 2.1 on 2020-04-16 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20200417_0220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='timings_perks',
            new_name='timings_and_perks',
        ),
    ]
