# Generated by Django 2.1 on 2020-04-19 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20200418_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='res_url',
            field=models.CharField(blank=True, max_length=2083, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='votes',
            field=models.CharField(blank=True, max_length=2083, null=True),
        ),
    ]
