# Generated by Django 2.1 on 2020-04-19 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20200419_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='votes',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
