# Generated by Django 2.1 on 2020-04-19 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20200419_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.CharField(max_length=2083, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='res_url',
            field=models.CharField(max_length=2083, null=True),
        ),
    ]
